"""new fields in user model

Revision ID: 77386ce04e71
Revises: 76096771ecbf
Create Date: 2025-06-22 21:11:48.787241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77386ce04e71'
down_revision = '76096771ecbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mb_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mb_users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
