"""model User to db-table mb_users

Revision ID: 8165fab68bf9
Revises: 
Create Date: 2025-06-20 11:28:49.864610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8165fab68bf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mb_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mb_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_mb_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mb_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mb_users_username'))
        batch_op.drop_index(batch_op.f('ix_mb_users_email'))

    op.drop_table('mb_users')
    # ### end Alembic commands ###
