"""notifications - 2

Revision ID: 8cdca26ce0cc
Revises: a455e6eb5b6c
Create Date: 2025-07-22 18:22:02.496444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cdca26ce0cc'
down_revision = 'a455e6eb5b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mb_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['mb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mb_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mb_notifications_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mb_notifications_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_mb_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_name'))
        batch_op.drop_index(batch_op.f('ix_notification_timestamp'))
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    op.drop_table('notification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.FLOAT(), nullable=False),
    sa.Column('payload_json', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['mb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_name'), ['name'], unique=False)

    with op.batch_alter_table('mb_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mb_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_mb_notifications_timestamp'))
        batch_op.drop_index(batch_op.f('ix_mb_notifications_name'))

    op.drop_table('mb_notifications')
    # ### end Alembic commands ###
