"""add language to posts

Revision ID: 9c0c29618adf
Revises: 3f91b3116628
Create Date: 2025-07-01 15:59:12.792444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0c29618adf'
down_revision = '3f91b3116628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mb_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mb_posts', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
