"""empty message

Revision ID: 0318d50a610e
Revises: 
Create Date: 2025-08-03 17:13:30.914033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0318d50a610e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mb_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mb_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_mb_users_username'), ['username'], unique=True)

    op.create_table('mb_followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['mb_users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['mb_users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('mb_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['mb_users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['mb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mb_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mb_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mb_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mb_messages_timestamp'), ['timestamp'], unique=False)

    op.create_table('mb_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['mb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mb_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mb_notifications_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mb_notifications_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_mb_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('mb_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['mb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mb_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mb_posts_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_mb_posts_user_id'), ['user_id'], unique=False)

    op.create_table('mb_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['mb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mb_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mb_tasks_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mb_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mb_tasks_name'))

    op.drop_table('mb_tasks')
    with op.batch_alter_table('mb_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mb_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_mb_posts_timestamp'))

    op.drop_table('mb_posts')
    with op.batch_alter_table('mb_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mb_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_mb_notifications_timestamp'))
        batch_op.drop_index(batch_op.f('ix_mb_notifications_name'))

    op.drop_table('mb_notifications')
    with op.batch_alter_table('mb_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mb_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_mb_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_mb_messages_recipient_id'))

    op.drop_table('mb_messages')
    op.drop_table('mb_followers')
    with op.batch_alter_table('mb_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mb_users_username'))
        batch_op.drop_index(batch_op.f('ix_mb_users_email'))

    op.drop_table('mb_users')
    # ### end Alembic commands ###
