"""taksk

Revision ID: 6a3b06607c03
Revises: 8cdca26ce0cc
Create Date: 2025-07-23 23:45:22.978246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3b06607c03'
down_revision = '8cdca26ce0cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mb_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['mb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mb_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mb_tasks_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mb_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mb_tasks_name'))

    op.drop_table('mb_tasks')
    # ### end Alembic commands ###
