"""posts table

Revision ID: 76096771ecbf
Revises: 8165fab68bf9
Create Date: 2025-06-20 22:33:18.184857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76096771ecbf'
down_revision = '8165fab68bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mb_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['mb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mb_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mb_posts_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_mb_posts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mb_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mb_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_mb_posts_timestamp'))

    op.drop_table('mb_posts')
    # ### end Alembic commands ###
